### ISSUE TITLE
Hi，When running this program with "sh scripts / icews14. Sh", the following error occurs.Maybe someone knows how to modify it?

### ISSUE THREAD

**Issue by yang123456457** [sharkmir1/T-GAP#1]
Traceback (most recent call last):
  File "main.py", line 207, in <module>
    main(args)
  File "main.py", line 195, in main
    global_count += train_one_epoch(model, train_dataloader, optimizer, args, epoch, global_count, summary_writer)
  File "main.py", line 33, in train_one_epoch
    attention_history = model(batch)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/T-GAP-master/model.py", line 153, in forward
    graph.apply_edges(fn.u_mul_e('a', 'transition', 'a_tilde'))
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/heterograph.py", line 4423, in apply_edges
    edata = core.invoke_gsddmm(g, func)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/core.py", line 241, in invoke_gsddmm
    z = op(graph, x, y)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/ops/sddmm.py", line 133, in func
    lhs_target=lhs_target, rhs_target=rhs_target)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/ops/sddmm.py", line 75, in gsddmm
    g._graph, op, lhs_data, rhs_data, lhs_target, rhs_target)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/backend/pytorch/sparse.py", line 428, in gsddmm
    return GSDDMM.apply(gidx, op, lhs_data, rhs_data, lhs_target, rhs_target)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 213, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/backend/pytorch/sparse.py", line 195, in forward
    out = _gsddmm(gidx, op, X, Y, lhs_target, rhs_target)
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/sparse.py", line 327, in _gsddmm
    infer_broadcast_shape(op, lhs_shp[1:], rhs_shp[1:])
  File "/home/.conda/envs/py37/lib/python3.7/site-packages/dgl/sparse.py", line 52, in infer_broadcast_shape
    .format(shp1, shp2))
dgl._ffi.base.DGLError: Feature shapes torch.Size([1, 16, 5]) and torch.Size([16, 5, 1]) are not valid for broadcasting.

**Comment by jaehunjung1** [comment]
Hi, can you share your DGL and torch version?

**Comment by yang123456457** [comment]
> Hi, can you share your DGL and torch version?

My torch version is 1.7.1.post2,and DGL version is 0.7.0.

**Comment by yang123456457** [comment]
> Hi, can you share your DGL and torch version?
This is really caused by different versions. After I changed DGL to version 0.4.2, the problem was solved!!
Thank you very much for your help!!
